AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Example Warehouse Management System with 4 Lambdas"

Globals:
  Function:
    Runtime: python3.9
    Timeout: 15
    MemorySize: 128
    Environment:
      Variables:
        MY_REGION: "us-east-2"
        STORING_ORDERS_TABLE: "StoringOrders"
        PACKAGES_TABLE: "Packages"
        PICKSLIPS_TABLE: "PickSlips"

Resources:
  ########################
  # API Gateway
  ########################
  WmsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  ########################
  # 1) StoringOrderValidityCheck 함수
  ########################
  StoringOrderValidityCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "storingOrderValidityCheck"
      CodeUri: src/storingOrderValidityCheck/
      Handler: handler.lambda_handler

      # 여기서 Policies를 지정 (또는 Role: <IAM Role ARN> 을 사용)
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess

      Events:
        CheckStoringOrderApi:
          Type: Api
          Properties:
            RestApiId: !Ref WmsApi
            Path: /storing-order/check
            Method: POST

  ########################
  # 2) PackageQuery 함수
  ########################
  PackageQueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "packageQuery"
      CodeUri: src/packageQuery/
      Handler: handler.lambda_handler

      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess

      Events:
        GetPackageApi:
          Type: Api
          Properties:
            RestApiId: !Ref WmsApi
            Path: /package
            Method: GET

  ########################
  # 3) PickSlipsScan 함수
  ########################
  PickSlipsScanFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "pickSlipsScan"
      CodeUri: src/pickSlipsScan/
      Handler: handler.lambda_handler

      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess

      Events:
        GetPickSlipsApi:
          Type: Api
          Properties:
            RestApiId: !Ref WmsApi
            Path: /pickslips
            Method: GET

  ########################
  # 4) StoringOrdersScan 함수
  ########################
  StoringOrdersScanFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "storingOrdersScan"
      CodeUri: src/storingOrdersScan/
      Handler: handler.lambda_handler

      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess

      Events:
        GetStoringOrdersApi:
          Type: Api
          Properties:
            RestApiId: !Ref WmsApi
            Path: /storing-orders
            Method: GET

  ########################
  # 5) PackagesScan 함수
  ########################
  PackagesScanFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "packagesScan"
      CodeUri: src/packagesScan/
      Handler: handler.lambda_handler

      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess

      Events:
        GetPackagesApi:
          Type: Api
          Properties:
            RestApiId: !Ref WmsApi
            Path: /packages
            Method: GET


  ########################
  # 6) GlueCrawlerRegister 함수 (API 없이 내부용)
  ########################
  GlueCrawlerRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "glueCrawlerRegister"
      CodeUri: src/glueCrawlerRegister/
      Handler: handler.handler  # 보통 Lambda 내부는 handler(event, context)

      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - glue:*
                - dynamodb:ListTables
                - iam:PassRole
              Resource: "*"

      # 이벤트가 없는 내부 트리거용 Lambda
      # 이후 EventBridge 트리거나 Step Functions로 연결 가능

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${WmsApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
